In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\Parth Patel\Downloads\raw_data_final.csv")
data

,incident_id,timestamp,area_name,incident_type,crowd_density,lighting_condition,police_nearby,weather_condition,transport_mode,report_delay_minutes
0,INC00001,2025-11-25 13:54:47,Andheri,Assault,61.0,NaN,Unknown,Foggy,Car,50.0
1,INC00002,2025-09-21 03:04:47,Banjara Hills,Assault,NaN,Poor,Unknown,Windy,NaN,NaN
2,INC00003,2025-12-18 03:30:47,MG Road,Assault,49.0,Moderate,Unknown,Foggy,Metro,212.0
3,INC00004,2025-09-30 10:57:47,Banjara Hills,Harassment,NaN,Poor,Unknown,Foggy,Bus,NaN
4,INC00005,2025-09-04 03:14:47,Salt Lake,Assault,NaN,Moderate,Unknown,Humid,Walking,183.0
...,...,...,...,...,...,...,...,...,...,...
1495,INC01496,2026-01-14 13:31:47,Banjara Hills,Assault,228.0,Moderate,No,Clear,Bike,NaN
1496,INC01497,2025-12-11 17:31:47,Indiranagar,Harassment,432.0,NaN,No,Windy,Metro,NaN
1497,INC01498,2025-12-14 12:53:47,NaN,Theft,NaN,NaN,Unknown,Foggy,Car,46.0
1498,INC01499,2025-10-13 12:48:47,NaN,Theft,NaN,NaN,Yes,Foggy,Walking,NaN
1499,INC01500,2025-08-25 08:32:47,Salt Lake,Suspicious Activity,220.0,NaN,Unknown,Foggy,Bike,NaN

In [3]:
data.head(15)

,incident_id,timestamp,area_name,incident_type,crowd_density,lighting_condition,police_nearby,weather_condition,transport_mode,report_delay_minutes
0,INC00001,2025-11-25 13:54:47,Andheri,Assault,61.0,NaN,Unknown,Foggy,Car,50.0
1,INC00002,2025-09-21 03:04:47,Banjara Hills,Assault,NaN,Poor,Unknown,Windy,NaN,NaN
2,INC00003,2025-12-18 03:30:47,MG Road,Assault,49.0,Moderate,Unknown,Foggy,Metro,212.0
3,INC00004,2025-09-30 10:57:47,Banjara Hills,Harassment,NaN,Poor,Unknown,Foggy,Bus,NaN
4,INC00005,2025-09-04 03:14:47,Salt Lake,Assault,NaN,Moderate,Unknown,Humid,Walking,183.0
5,INC00006,2025-09-10 11:49:47,Salt Lake,Pickpocketing,NaN,Poor,Yes,Clear,NaN,41.0
6,INC00007,2025-08-29 11:04:47,Salt Lake,Pickpocketing,NaN,Poor,Yes,Windy,Bus,181.0
7,INC00008,2025-10-09 22:21:47,NaN,Harassment,NaN,NaN,Yes,Foggy,Walking,NaN
8,INC00009,2025-08-31 02:39:47,Whitefield,Theft,NaN,Poor,No,Windy,Metro,88.0
9,INC00010,2025-11-19 02:51:47,Indiranagar,Assault,NaN,Good,Unknown,Foggy,Bus,138.0
10,INC00011,2025-10-19 18:45:47,Whitefield,Pickpocketing,438.0,Poor,Yes,Foggy,Car,NaN
11,INC00012,2026-01-03 02:42:47,Connaught Place,Pickpocketing,NaN,NaN,No,Clear,Car,NaN
12,INC00013,2025-10-27 23:01:47,NaN,Suspicious Activity,NaN,Moderate,Unknown,Windy,Walking,NaN
13,INC00014,2025-08-17 00:05:47,Salt Lake,Harassment,NaN,Poor,Unknown,Clear,Bus,11.0
14,INC00015,2025-11-22 10:15:47,Salt Lake,Suspicious Activity,NaN,NaN,No,Windy,Metro,184.0

In [4]:
data['timestamp'] = pd.to_datetime(data['timestamp'])

In [5]:
data.head(15)

,incident_id,timestamp,area_name,incident_type,crowd_density,lighting_condition,police_nearby,weather_condition,transport_mode,report_delay_minutes
0,INC00001,2025-11-25 13:54:47,Andheri,Assault,61.0,NaN,Unknown,Foggy,Car,50.0
1,INC00002,2025-09-21 03:04:47,Banjara Hills,Assault,NaN,Poor,Unknown,Windy,NaN,NaN
2,INC00003,2025-12-18 03:30:47,MG Road,Assault,49.0,Moderate,Unknown,Foggy,Metro,212.0
3,INC00004,2025-09-30 10:57:47,Banjara Hills,Harassment,NaN,Poor,Unknown,Foggy,Bus,NaN
4,INC00005,2025-09-04 03:14:47,Salt Lake,Assault,NaN,Moderate,Unknown,Humid,Walking,183.0
5,INC00006,2025-09-10 11:49:47,Salt Lake,Pickpocketing,NaN,Poor,Yes,Clear,NaN,41.0
6,INC00007,2025-08-29 11:04:47,Salt Lake,Pickpocketing,NaN,Poor,Yes,Windy,Bus,181.0
7,INC00008,2025-10-09 22:21:47,NaN,Harassment,NaN,NaN,Yes,Foggy,Walking,NaN
8,INC00009,2025-08-31 02:39:47,Whitefield,Theft,NaN,Poor,No,Windy,Metro,88.0
9,INC00010,2025-11-19 02:51:47,Indiranagar,Assault,NaN,Good,Unknown,Foggy,Bus,138.0
10,INC00011,2025-10-19 18:45:47,Whitefield,Pickpocketing,438.0,Poor,Yes,Foggy,Car,NaN
11,INC00012,2026-01-03 02:42:47,Connaught Place,Pickpocketing,NaN,NaN,No,Clear,Car,NaN
12,INC00013,2025-10-27 23:01:47,NaN,Suspicious Activity,NaN,Moderate,Unknown,Windy,Walking,NaN
13,INC00014,2025-08-17 00:05:47,Salt Lake,Harassment,NaN,Poor,Unknown,Clear,Bus,11.0
14,INC00015,2025-11-22 10:15:47,Salt Lake,Suspicious Activity,NaN,NaN,No,Windy,Metro,184.0

In [6]:
categorical_cols = ['area_name', 'lighting_condition', 'transport_mode']
for col in categorical_cols:
    data[col] = data[col].fillna('Unknown')

In [7]:
data

,incident_id,timestamp,area_name,incident_type,crowd_density,lighting_condition,police_nearby,weather_condition,transport_mode,report_delay_minutes
0,INC00001,2025-11-25 13:54:47,Andheri,Assault,61.0,Unknown,Unknown,Foggy,Car,50.0
1,INC00002,2025-09-21 03:04:47,Banjara Hills,Assault,NaN,Poor,Unknown,Windy,Unknown,NaN
2,INC00003,2025-12-18 03:30:47,MG Road,Assault,49.0,Moderate,Unknown,Foggy,Metro,212.0
3,INC00004,2025-09-30 10:57:47,Banjara Hills,Harassment,NaN,Poor,Unknown,Foggy,Bus,NaN
4,INC00005,2025-09-04 03:14:47,Salt Lake,Assault,NaN,Moderate,Unknown,Humid,Walking,183.0
...,...,...,...,...,...,...,...,...,...,...
1495,INC01496,2026-01-14 13:31:47,Banjara Hills,Assault,228.0,Moderate,No,Clear,Bike,NaN
1496,INC01497,2025-12-11 17:31:47,Indiranagar,Harassment,432.0,Unknown,No,Windy,Metro,NaN
1497,INC01498,2025-12-14 12:53:47,Unknown,Theft,NaN,Unknown,Unknown,Foggy,Car,46.0
1498,INC01499,2025-10-13 12:48:47,Unknown,Theft,NaN,Unknown,Yes,Foggy,Walking,NaN
1499,INC01500,2025-08-25 08:32:47,Salt Lake,Suspicious Activity,220.0,Unknown,Unknown,Foggy,Bike,NaN

In [9]:
data['crowd_density'] = data['crowd_density'].fillna(data['crowd_density'].median())
data['report_delay_minutes'] = data['report_delay_minutes'].fillna(data['report_delay_minutes'].median())

In [10]:
data

,incident_id,timestamp,area_name,incident_type,crowd_density,lighting_condition,police_nearby,weather_condition,transport_mode,report_delay_minutes
0,INC00001,2025-11-25 13:54:47,Andheri,Assault,61.0,Unknown,Unknown,Foggy,Car,50.0
1,INC00002,2025-09-21 03:04:47,Banjara Hills,Assault,249.0,Poor,Unknown,Windy,Unknown,115.0
2,INC00003,2025-12-18 03:30:47,MG Road,Assault,49.0,Moderate,Unknown,Foggy,Metro,212.0
3,INC00004,2025-09-30 10:57:47,Banjara Hills,Harassment,249.0,Poor,Unknown,Foggy,Bus,115.0
4,INC00005,2025-09-04 03:14:47,Salt Lake,Assault,249.0,Moderate,Unknown,Humid,Walking,183.0
...,...,...,...,...,...,...,...,...,...,...
1495,INC01496,2026-01-14 13:31:47,Banjara Hills,Assault,228.0,Moderate,No,Clear,Bike,115.0
1496,INC01497,2025-12-11 17:31:47,Indiranagar,Harassment,432.0,Unknown,No,Windy,Metro,115.0
1497,INC01498,2025-12-14 12:53:47,Unknown,Theft,249.0,Unknown,Unknown,Foggy,Car,46.0
1498,INC01499,2025-10-13 12:48:47,Unknown,Theft,249.0,Unknown,Yes,Foggy,Walking,115.0
1499,INC01500,2025-08-25 08:32:47,Salt Lake,Suspicious Activity,220.0,Unknown,Unknown,Foggy,Bike,115.0

In [12]:
data = data.drop_duplicates()

In [13]:
data

,incident_id,timestamp,area_name,incident_type,crowd_density,lighting_condition,police_nearby,weather_condition,transport_mode,report_delay_minutes
0,INC00001,2025-11-25 13:54:47,Andheri,Assault,61.0,Unknown,Unknown,Foggy,Car,50.0
1,INC00002,2025-09-21 03:04:47,Banjara Hills,Assault,249.0,Poor,Unknown,Windy,Unknown,115.0
2,INC00003,2025-12-18 03:30:47,MG Road,Assault,49.0,Moderate,Unknown,Foggy,Metro,212.0
3,INC00004,2025-09-30 10:57:47,Banjara Hills,Harassment,249.0,Poor,Unknown,Foggy,Bus,115.0
4,INC00005,2025-09-04 03:14:47,Salt Lake,Assault,249.0,Moderate,Unknown,Humid,Walking,183.0
...,...,...,...,...,...,...,...,...,...,...
1495,INC01496,2026-01-14 13:31:47,Banjara Hills,Assault,228.0,Moderate,No,Clear,Bike,115.0
1496,INC01497,2025-12-11 17:31:47,Indiranagar,Harassment,432.0,Unknown,No,Windy,Metro,115.0
1497,INC01498,2025-12-14 12:53:47,Unknown,Theft,249.0,Unknown,Unknown,Foggy,Car,46.0
1498,INC01499,2025-10-13 12:48:47,Unknown,Theft,249.0,Unknown,Yes,Foggy,Walking,115.0
1499,INC01500,2025-08-25 08:32:47,Salt Lake,Suspicious Activity,220.0,Unknown,Unknown,Foggy,Bike,115.0

In [15]:
data.to_csv('cleaned_data.csv', index=False)

In [16]:
print("Data cleaning complete. File saved as 'cleaned_data.csv'.")

Data cleaning complete. File saved as 'cleaned_data.csv'.